### ISSUE TITLE
Task component in Edge

### ISSUE THREAD

**Issue by oscarotero** [marketgoo/Ola#10]
Microsoft Edge [does not support the `<summary>` element](https://caniuse.com/#feat=details), so the Task component is always opened.

Fortunally, there's a polyfill to bring support in this browser, so we should check whether the Task component works with the polyfill loaded: https://github.com/javan/details-element-polyfill and add this info to the documentation in README.md

The next version of Edge will come with fully support for `<summary>`, so this is a temporary solution.

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/377873/65699544-8a29b100-e07e-11e9-88ef-0a65d3fd2847.png">

**Comment by pedroparra** [comment]
Readme updated in #26
