### ISSUE TITLE
Lastest version, 0.5.0-beta-7, breaks the tables

### ISSUE THREAD

**Issue by diego-pascual** [marketgoo/Ola#102]
<img width="405" alt="Captura de pantalla 2020-03-18 a las 12 28 31" src="https://user-images.githubusercontent.com/29247073/76956386-3f457380-6914-11ea-930d-d9b0b31ca9b0.png">
<img width="693" alt="Captura de pantalla 2020-03-18 a las 12 26 59" src="https://user-images.githubusercontent.com/29247073/76956389-4076a080-6914-11ea-8898-1fcbd353622e.png">

**Comment by oscarotero** [comment]
Fixed.
I've changed also the `TableCell variant=action` to ensure that is always visible.
