### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by diego-pascual** [marketgoo/Ola#109]
<img width="437" alt="Captura de pantalla 2020-04-14 a las 15 31 56" src="https://user-images.githubusercontent.com/29247073/79230645-3a1d0b00-7e65-11ea-99f9-428d58d6645e.png">
<img width="506" alt="Captura de pantalla 2020-04-14 a las 15 32 04" src="https://user-images.githubusercontent.com/29247073/79230652-3be6ce80-7e65-11ea-995b-4238e7df1ce5.png">

**Comment by oscarotero** [comment]
@diego-pascual For those cases, we can add a prop to force a position. Something like:

```jsx
//Force always the position top right
<Tooltip position="top right" />

//Force only the position y to top, and calculate the position x automatically
<Tooltip position="top" />

//Calculate the position x and y automatically
<Tooltip />
```

What do you think?

**Comment by diego-pascual** [comment]
@oscarotero there are situations where the tooltip doesn't show right in any position (see picture). I think the problem is something with position or z-index props or container elements. I don't know. I'll look into it when I can.
<img width="563" alt="Captura de pantalla 2020-04-15 a las 12 14 14" src="https://user-images.githubusercontent.com/29247073/79326426-1d3f1100-7f13-11ea-9b3d-73412bcb6e29.png">
