### ISSUE TITLE
PanelContent should be more separated 

### ISSUE THREAD

**Issue by pedroparra** [marketgoo/Ola#115]
![Captura de pantalla 2020-04-22 a las 12 39 30](https://user-images.githubusercontent.com/3930607/79972556-6accf800-8496-11ea-8033-5cb6f48c76b5.png)
Quizás deberíamos hacer que un PanelContent seguido de otro PanelContent tuviera un margen que ahora no tiene.

**Comment by oscarotero** [comment]
This should be fixed in #114
