### ISSUE TITLE
Fix ModalFooter and PanelFooter for support childrens when is used with ButtonGroup

### ISSUE THREAD

**Issue by pedroparra** [marketgoo/Ola#116]
![Captura de pantalla 2020-04-22 a las 18 30 25](https://user-images.githubusercontent.com/3930607/80009639-a2a16300-84c9-11ea-9f55-941444ee1fc3.png)

**Comment by oscarotero** [comment]
Fixed in https://github.com/marketgoo/Ola/commit/9fcfd6ccdd4318536e522f68c2e8680e7e314141
