### ISSUE TITLE
Check component should have less opacity when is disabled.

### ISSUE THREAD

**Issue by pedroparra** [marketgoo/Ola#117]
![Captura de pantalla 2020-04-23 a las 12 49 38](https://user-images.githubusercontent.com/3930607/80091353-425e0000-8561-11ea-87bc-9af291cf101e.png)
Check component should have less opacity when is disabled like this capture from design.

**Comment by pedroparra** [comment]
Add a variant too for change text size children perhaps ...

**Comment by oscarotero** [comment]
The opacity is right. More opacity may be confused with unchecked checkarea. And text size seems ok too, it should be 14px, (caption)

**Comment by pedroparra** [comment]
@oscarotero This image is a capture from sketch design. Component does not have any opacity and text appears more big.

**Comment by oscarotero** [comment]
Ah, ok. Styles for disable checks are missing.

**Comment by oscarotero** [comment]
- [x] Added styles for disabled state
- [x] Changed the way to apply the styles to the label. Now you can use the `ola-*` class helpers to change the text size of the label. For example: `<Check className="ola-caption" />`
