### ISSUE TITLE
Table: padding rigth 

### ISSUE THREAD

**Issue by griselmatosm** [marketgoo/Ola#143]
Inside Increase your Popularity menu there is a disalign row. We have discovered there is a css selector where could be causes the issue.
`.ola_tableCell {
    &:last-child {
        padding-right: 0;
    }`
![image](https://user-images.githubusercontent.com/60382139/87687785-71fa5e00-c786-11ea-927d-43a94bc3b665.png)

**Comment by oscarotero** [comment]
I think this problem is in the html of the app, not in the component. See https://3.basecamp.com/4423421/buckets/17436305/todos/2848666681#__recording_2859195564
