### ISSUE TITLE
Create a title prop in TreeList

### ISSUE THREAD

**Issue by pedroparra** [marketgoo/Ola#185]
![Screenshot 2021-03-23 at 11 47 18](https://user-images.githubusercontent.com/3930607/112135075-ae137780-8bcd-11eb-9af3-4305a9fdde91.png)

**Comment by pedroparra** [comment]
What do you think about this @oscarotero ?

**Comment by oscarotero** [comment]
@pedroparra IMO, I don't think we need this for now. It can be done with a simple `<p>` and I think it should be independent of the treelist.
