### ISSUE TITLE
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by pedroparra** [marketgoo/Ola#206]
![Screenshot 2021-06-07 at 20 09 33](https://user-images.githubusercontent.com/3930607/121068260-577d0900-c7cc-11eb-94d6-bf246d10d11e.png)

Level component is usually used inside the Page component and causes this warning:

![Screenshot 2021-06-07 at 20 11 22](https://user-images.githubusercontent.com/3930607/121068418-8dba8880-c7cc-11eb-9273-b92becae5452.png)

**Comment by oscarotero** [comment]
Maybe `ola_level` should be a span.
