### ISSUE TITLE
Warning on Button, Invalid prop `variant` of value `link` supplied to `Button` (version 0.2.0)

### ISSUE THREAD

**Issue by diego-pascual** [marketgoo/Ola#43]
I checked this in the repository and "link" appears as new value, however, when I update lib via npm, in the dist/Button folder it doesn't appear 

<img width="1147" alt="Captura de pantalla 2019-11-25 a las 16 14 17" src="https://user-images.githubusercontent.com/29247073/69552456-c6a25c00-0f9e-11ea-8464-2cbb005455af.png">

**Comment by pedroparra** [comment]
@diego-pascual Could it be that the version in the application is not updated correctly?

**Comment by oscarotero** [comment]
To upgrade from v0.1.x -> v0.2.x, you need to edit the `package.json` and run a `npm install` (no `npm update`.
