### ISSUE TITLE
Accordion component does not appear runs correctly in Safari

### ISSUE THREAD

**Issue by diego-pascual** [marketgoo/Ola#61]
<img width="616" alt="Captura de pantalla 2019-12-19 a las 9 54 44" src="https://user-images.githubusercontent.com/29247073/71159368-cc116000-2245-11ea-8efd-7534b65073d1.png">
<img width="359" alt="Captura de pantalla 2019-12-19 a las 9 54 36" src="https://user-images.githubusercontent.com/29247073/71159369-cc116000-2245-11ea-8e8b-283dc1865522.png">

**Comment by oscarotero** [comment]
@diego-pascual Fixed. It's because Safari does not support `display: inline-flex` applied directly to a `summary`, I had to create a inner `<div>`.
