### ISSUE TITLE
Adjust margin in Task for responsive

### ISSUE THREAD

**Issue by diego-pascual** [marketgoo/Ola#63]
<img width="328" alt="Captura de pantalla 2019-12-19 a las 10 01 49" src="https://user-images.githubusercontent.com/29247073/71159827-b51f3d80-2246-11ea-936f-71b9b9483230.png">

**Comment by oscarotero** [comment]
Ok, added the viewport plugin to storybook and reduzed the margins in narrow screens (https://marketgoo.github.io/Ola/?path=/story/task--error)
