### ISSUE TITLE
Modal improvements

### ISSUE THREAD

**Issue by diego-pascual** [marketgoo/Ola#74]
- Allow to close the modal clicked out
- Allow to close the modal with esc key
- On mobile devices the modal padding is very high. It's better to give a smaller padding to take more advantage of the screen.

**Comment by oscarotero** [comment]
The modal behaviour is not controlled by Ola, so the two first points cannot be fixed here but in the library you use to open/close the modal (right, @pedroparra ?)

The third point is ok, I'll take a look.

**Comment by pedroparra** [comment]
@oscarotero Exactly that's it. We could try using the html dialog tag as we speak at first.

**Comment by diego-pascual** [comment]
It's just adding the events, the same way the event is when you click on the close icon. The modal trigger/controller is still outside the component. Look at it in the PR @oscarotero @pedroparra
