### ISSUE TITLE
ola_buttonIcon isn't vertically centered

### ISSUE THREAD

**Issue by diego-pascual** [marketgoo/Ola#84]
If you use the ButtonIcon component on a table, the icon isn't centered vertically. it can be fixed by adding `vertical-align: middle;`
<img width="440" alt="Captura de pantalla 2020-03-03 a las 16 20 28" src="https://user-images.githubusercontent.com/29247073/75790082-f665ba80-5d6a-11ea-80b0-4be76c69638c.png">

**Comment by oscarotero** [comment]
Good catch! Fixed
